baseURL = 'https://garrettflynn.com/andrew/'
languageCode = 'en-us'
title = 'A.BRILLIANT FILM'
theme = 'abrilliant'

[params]
  description = 'Multi-media storytellers based in Los Angeles, CA'
  author = 'Andrew Wyatt Brilliant'
  tagline = 'MULTI-MEDIA STORYTELLERS'
  location = 'Based in Los Angeles, CA'
  email = 'info@abrilliantfilm.com'
  copyright = 'PROPERTY OF ANDREW WYATT BRILLIANT'

  # Social media links (customize as needed)
  [params.social]
    instagram = ''
    vimeo = ''
    youtube = ''
    linkedin = ''

[menu]
  [[menu.main]]
    name = 'Portfolio'
    url = 'portfolio/'
    weight = 1
  [[menu.main]]
    name = 'Contact'
    url = 'contact/'
    weight = 2
  [[menu.main]]
    name = 'About'
    url = 'about/'
    weight = 3

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
